version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins-docker
    privileged: true
    restart: always
    user: root
    ports:
      - 8082:443
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./jenkins.jks:/var/lib/jenkins/jenkins.jks
    environment:
      JAVA_OPTS: -Duser.timezone=CET
      JENKINS_OPTS: --httpPort=-1 --httpsPort=443 --httpsKeyStore=/var/lib/jenkins/jenkins.jks --httpsKeyStorePassword=password