port_pgsql = ENV["VAGRANT_PGSQL_PORT"] || 5432
port_pgadmin = ENV["VAGRANT_PGADMIN_PORT"] || 16543

Vagrant.configure("2") do |config|
    config.vm.network "public_network"
    config.vm.network "forwarded_port", guest: 5432, host: port_pgsql
    config.vm.network "forwarded_port", guest: 16543, host: port_pgadmin
    config.vm.define "db-pgsql-srv" do |server|
        server.vm.box = "ubuntu/xenial64"
		server.vm.box_version = "20211001.0.0"
        server.vm.hostname = "db-pgsql-srv"
        server.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
            vb.cpus = "4"
            vb.name = "db-pgsql-srv"
        end
    end
end