Vagrant.configure("2") do |config|
    config.vm.network "public_network"
    config.vm.define "db-mssql-srv" do |server|
        server.vm.box = "ubuntu/xenial64"
		server.vm.box_version = "20211001.0.0"
        server.vm.hostname = "db-mssql-srv"
        server.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
            vb.cpus = "4"
            vb.name = "db-mssql-srv"
        end
    end
end